### ISSUE TITLE
NPE/UserRecoverableAuthIOException, Cause=AppDownloadRequired after updating google-play-services.jar

### ISSUE THREAD

**Issue by alsacool** [googlearchive/drive-appdatapreferences-android#2]
I replaced google-play-services.jar in appdatapreferences-android\libs with the latest from Android SDK.
The appdatapreferences-android-boostrap app still runs fine, prompts for user permission the first time, and syncs periodically thereafter. 

However, after the app is dismissed using the back button, a crash occurs on the next periodic sync. 
This did not happen with the original google-play-services.jar included in the project.

The sync operation generates a new UserRecoverableAuthIOException (this was not the case with the original google-play-services.jar).
The exception cause is not NeedPermission but instead is AppDownloadRequired
A Null Pointer Exception then occurs in SettingsActivity's onUserRecoverableAuthException at startActivityForResult().

(The motivation for updating google-play-services.jar is because my target app uses the latest and adding a reference to appdatapreferences-android library project resulted in error "Found 2 versions of google-play-services.jar, but not all the versions are identical")

05-30 07:32:52.850: D/preferences(3350): Refreshing the screen
05-30 07:33:08.356: D/syncer(3350): Updating the remote preferences file
05-30 07:33:08.356: W/AbstractGoogleClient(3350): Application name is not set. Call Builder#setApplicationName.
05-30 07:33:08.797: D/dalvikvm(3350): GC_CONCURRENT freed 1726K, 19% free 9746K/12003K, paused 2ms+2ms
05-30 07:33:10.208: D/preferences(3350): Refreshing the screen

<<< BACK button pressed >>>

05-30 07:33:17.616: W/IInputConnectionWrapper(3350): showStatusIcon on inactive InputConnection
05-30 07:33:17.636: D/OpenGLRenderer(3350): Flushing caches (mode 0)
05-30 07:33:17.636: D/memalloc(3350): ion: Unmapping buffer  base:0x5098d000 size:1949696
05-30 07:33:17.636: D/memalloc(3350): ion: Unmapping buffer  base:0x50f1a000 size:1949696
05-30 07:33:17.636: D/memalloc(3350): ion: Unmapping buffer  base:0x510f6000 size:1949696
05-30 07:33:18.067: D/OpenGLRenderer(3350): Flushing caches (mode 1)
05-30 07:33:18.557: D/syncer(3350): Syncing the preferences....
05-30 07:33:18.557: D/syncer(3350): Updating the local preferences file
05-30 07:33:18.567: W/AbstractGoogleClient(3350): Application name is not set. Call Builder#setApplicationName.
05-30 07:33:18.577: D/preferences(3350): Ask for permissions
05-30 07:33:18.577: W/dalvikvm(3350): threadid=13: thread exiting with uncaught exception (group=0x40ace9f0)
05-30 07:33:18.587: E/AndroidRuntime(3350): FATAL EXCEPTION: SyncAdapterThread-2
05-30 07:33:18.587: E/AndroidRuntime(3350): java.lang.NullPointerException
05-30 07:33:18.587: E/AndroidRuntime(3350):     at android.content.Intent.<init>(Intent.java:3111)
05-30 07:33:18.587: E/AndroidRuntime(3350):     at com.google.android.gms.auth.UserRecoverableAuthException.getIntent(Unknown Source)
05-30 07:33:18.587: E/AndroidRuntime(3350):     at com.google.api.client.googleapis.extensions.android.gms.auth.UserRecoverableAuthIOException.getIntent(UserRecoverableAuthIOException.java:59)
05-30 07:33:18.587: E/AndroidRuntime(3350):     at com.google.drive.samples.appdatapreferencesdemo.SettingsActivity.onUserRecoverableAuthException(SettingsActivity.java:144)
05-30 07:33:18.587: E/AndroidRuntime(3350):     at com.google.drive.appdatapreferences.AppdataPreferencesSyncer.handleException(AppdataPreferencesSyncer.java:237)
05-30 07:33:18.587: E/AndroidRuntime(3350):     at com.google.drive.appdatapreferences.AppdataPreferencesSyncer.sync(AppdataPreferencesSyncer.java:112)
05-30 07:33:18.587: E/AndroidRuntime(3350):     at com.google.drive.appdatapreferences.AppdataSyncerAdapter.onPerformSync(AppdataSyncerAdapter.java:58)
05-30 07:33:18.587: E/AndroidRuntime(3350):     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)

**Comment by rakyll** [comment]
I'd recommend you to clone this lib project, add it as a dependency and replace `google-play-services.jar`. I'll provide an up-to-date binary as soon as possible.

**Comment by alsacool** [comment]
I think I did just that and get the crash. Cloned both AppdataPreferences and AppdataPreferences Bootstrap per [Setup instructions](https://github.com/googledrive/appdatapreferences-android-bootstrap#setup). Replaced `google-play-services.jar` in appdatapreferences-android\libs with `google-play-services.jar` revision 7 from Android SDK.
Are you saying that you need to generate your own version of `google-play-services.jar` or that the appdatapreferences-android source needs to be updated to work with latest `google-play-services.jar` ? 
Is there any documentation detailing the different `UserRecoverableAuthIOException` causes and in which situations they are thrown? Thanks

**Comment by alsacool** [comment]
I was able to eliminate this issue by using the application's context instead of the activity when creating the GoogleAccountCredential in the AppdataPreferences Bootstrap `SettingsActivity`, `onCreate()` method:

```
    GoogleAccountCredential credential =
        GoogleAccountCredential.usingOAuth2(this.getApplicationContext(), "https://www.googleapis.com/auth/drive.appdata");
```

Can you confirm this is a valid fix?

**Comment by rakyll** [comment]
It's a valid solution. AppdataSyncerAdapter's context should be inited with the application's context, since the lifetime of the syncer is beyond the activity's lifetime.
