### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cbrulak** [googlearchive/drive-appdatapreferences-android#4]
Two stacktraces:
E/AndroidRuntime( 3202): FATAL EXCEPTION: AsyncTask #3
E/AndroidRuntime( 3202): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 3202):    at android.os.AsyncTask$3.done(AsyncTask.java:299)
E/AndroidRuntime( 3202):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
E/AndroidRuntime( 3202):    at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
E/AndroidRuntime( 3202):    at java.util.concurrent.FutureTask.run(FutureTask.java:239)
E/AndroidRuntime( 3202):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
E/AndroidRuntime( 3202):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/AndroidRuntime( 3202):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/AndroidRuntime( 3202):    at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime( 3202): Caused by: java.lang.OutOfMemoryError
E/AndroidRuntime( 3202):    at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
E/AndroidRuntime( 3202):    at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:124)
E/AndroidRuntime( 3202):    at java.lang.StringBuilder.append(StringBuilder.java:271)
E/AndroidRuntime( 3202):    at com.google.gson.stream.JsonReader.nextString(JsonReader.java:1032)
E/AndroidRuntime( 3202):    at com.google.gson.stream.JsonReader.nextValue(JsonReader.java:784)
E/AndroidRuntime( 3202):    at com.google.gson.stream.JsonReader.objectValue(JsonReader.java:766)
E/AndroidRuntime( 3202):    at com.google.gson.stream.JsonReader.peek(JsonReader.java:380)
E/AndroidRuntime( 3202):    at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:54)
E/AndroidRuntime( 3202):    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
E/AndroidRuntime( 3202):    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
E/AndroidRuntime( 3202):    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:146)
E/AndroidRuntime( 3202):    at com.google.gson.Gson.fromJson(Gson.java:755)
E/AndroidRuntime( 3202):    at com.google.gson.Gson.fromJson(Gson.java:721)
E/AndroidRuntime( 3202):    at com.google.gson.Gson.fromJson(Gson.java:670)
E/AndroidRuntime( 3202):    at com.google.drive.appdatapreferences.AppdataPreferencesSyncer.updateLocal(AppdataPreferencesSyncer.java:218)
E/AndroidRuntime( 3202):    at com.google.drive.appdatapreferences.AppdataPreferencesSyncer.sync(AppdataPreferencesSyncer.java:109)

and

E/dalvikvm-heap( 3202): Out of memory on a 9033410-byte allocation.
I/dalvikvm( 3202): "AsyncTask #3" prio=5 tid=21 RUNNABLE
I/dalvikvm( 3202):   | group="main" sCount=0 dsCount=0 obj=0x41c4ab88 self=0x61c69468
I/dalvikvm( 3202):   | sysTid=4283 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1074332888
I/dalvikvm( 3202):   | state=R schedstat=( 3796668000 1838199000 14458 ) utm=330 stm=49 core=3
I/dalvikvm( 3202):   at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:~94)
I/dalvikvm( 3202):   at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:124)
I/dalvikvm( 3202):   at java.lang.StringBuilder.append(StringBuilder.java:271)
I/dalvikvm( 3202):   at com.google.gson.stream.JsonReader.nextString(JsonReader.java:1032)
I/dalvikvm( 3202):   at com.google.gson.stream.JsonReader.nextValue(JsonReader.java:784)
I/dalvikvm( 3202):   at com.google.gson.stream.JsonReader.objectValue(JsonReader.java:766)
I/dalvikvm( 3202):   at com.google.gson.stream.JsonReader.peek(JsonReader.java:380)
I/dalvikvm( 3202):   at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:54)
I/dalvikvm( 3202):   at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
I/dalvikvm( 3202):   at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
I/dalvikvm( 3202):   at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:146)
I/dalvikvm( 3202):   at com.google.gson.Gson.fromJson(Gson.java:755)
I/dalvikvm( 3202):   at com.google.gson.Gson.fromJson(Gson.java:721)
I/dalvikvm( 3202):   at com.google.gson.Gson.fromJson(Gson.java:670)
I/dalvikvm( 3202):   at com.google.drive.appdatapreferences.AppdataPreferencesSyncer.updateLocal(AppdataPreferencesSyncer.java:218)
I/dalvikvm( 3202):   at com.google.drive.appdatapreferences.AppdataPreferencesSyncer.sync(AppdataPreferencesSyncer.java:109)
I/dalvikvm( 3202):   at com.brulak.android.plasma.LoginActivity$ForceSyncAsyncTask.doInBackground(LoginActivity.java:459)
I/dalvikvm( 3202):   at com.brulak.android.plasma.LoginActivity$ForceSyncAsyncTask.doInBackground(LoginActivity.java:450)
I/dalvikvm( 3202):   at android.os.AsyncTask$2.call(AsyncTask.java:287)
I/dalvikvm( 3202):   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
I/dalvikvm( 3202):   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
I/dalvikvm( 3202):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
I/dalvikvm( 3202):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
I/dalvikvm( 3202):   at java.lang.Thread.run(Thread.java:856)

Symptoms/situation: 

Ran a force sync of preferences on a network with bad wifi. This may have been a weak signal or a port was blocked (does drive use any other port than 80?).

**Comment by rakyll** [comment]
I havent taken a look at the issue but all Drive API calls are secure and all destination ports are 443.

**Comment by cbrulak** [comment]
pretty sure this was something to do with wifi, not this lib.
